### PR TITLE
Re-Dyeing for Items

### PR DESCRIPTION
**Pull request by MilaDog**
I have been throughly enjoying the mod. 

Yet, with the time I have spent using it, I have found it a schlep not having the option to re-dye a made hammock/sleeping bag.
The original mod allowed for the dyeing of the White Sleeping Bag/Hammock into different colours. I found this the schlep and went ahead and added the ability to re-dye the items, so I need not make a new hammock for the desired colour (and of course have multiple items in storage) (Includes beds)

Purely just a QOL improvement that I wish to see implemented.

### CODE REVIEW

**Review by TheIllusiveC4 — CHANGES_REQUESTED** [review]
Please remove the bed recipes as that is outside the scope of the mod.

Also, each dyeing recipe needs to be tagged. In this case, since Fabric and Forge have different tagging schemes, I would like to fallback to Fabric's. So, for example, any `"item": "minecraft:blue_dye"` entries should be changed to `"tag": "c:blue_dyes"`. You can find a list of those tag names here: https://github.com/illusivesoulworks/comforts/tree/1.19.x/fabric/src/main/resources/data/c/tags/items

**Comment by MilaDog** [comment]
Thank you for the reply.

I shall do the necessary changes.

Also, why is it done this way? Conventions for modding?

**Comment by TheIllusiveC4** [comment]
> Also, why is it done this way? Conventions for modding?

What are you referring to exactly?

**Comment by MilaDog** [comment]
The tagging scheme. So that you made reference to

**Comment by TheIllusiveC4** [comment]
It's considered good practice to use tags when feasible, and both Forge and Fabric have a namespace for all mods to share. This makes it easier for mods to be compatible with one another. As an example, by switching to tags in this case other mods that have their own dye items and have tagged them appropriately will automatically be compatible with these recipes.

**Comment by MilaDog** [comment]
Hopefully I covered what you would like :)

**Comment by TheIllusiveC4** [comment]
Yes, looks good, thank you.

**Review by TheIllusiveC4 — APPROVED** [review]

**Pull request merged**
