### PR TITLE
Create tr_tr.lang

### PR DESCRIPTION
**Pull request by Emirhangg**
Made by: Emirhangg
Turkish Language.

### CODE REVIEW

**Comment by TheIllusiveC4** [comment]
Thank you very much!

**Comment by TheIllusiveC4** [comment]
There seems to be some error-ed characters in the formatting? It's hard for me to tell because I don't know Unicode symbols nor Turkish characters. Can you look it over and make an updated PR once you get the chance? I'll keep the file as is for now since an almost complete translation is better than none at all.

**Comment by Emirhangg** [comment]
I don't know how i will download from GitHub. But i will send you a pure file.
[tr_tr.zip](https://github.com/TheIllusiveC4/Comforts/files/2095711/tr_tr.zip)

**Comment by TheIllusiveC4** [comment]
Okay, that seems to be working fine. Thanks for your contribution.

**Pull request merged**
